// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etswptyoedcahtirnush.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0c3dwdHlvZWRjYWh0aXJudXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEwMTUsImV4cCI6MjA2NTQ2NzAxNX0.ubh6GKDHuuD5CIR6ZFbF_yNQBh5LyR2RUCDi8CN0KTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);